name = "Basepack"
author = "verbina29"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4213384b89473a6ebb37bf99adce3972cf809f2831e22a8fb66a78d9d05704d0"

[versions]
fabric = "0.16.2"
minecraft = "1.19.2"
